### ISSUE TITLE
Document these use cases

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine-docs#1]
This is a overall issue list. 

List of use-cases that should be captured in docs:
- [x] Handle anonymous (not logged in) user permissions
- [x] Schema stitching example
- [x] Relationships
- [x] Enums
- [x] Computed fields / derived data (should be SEO terms for views)

Authentication and user handling guides:
- [ ] Auth0, Firebase, ForgeRock
- [x] Auth webhook examples for different use-cases
- [ ] Where does user profile data go?

Modelling different types of permissions:
- [x] Collaborators
- [x] Multi-tenant

Different types of data-modelling:
- [ ] one-one
- [ ] one-many
- [ ] many-many
- [ ] ENUMS

**Comment by wieseljonas** [comment]
Would be great to see more info about enums!

**Comment by DrewMcArthur** [comment]
@coco98 would also love to see info on enums.  Specifically how to implement that from the web portal?  For example in a `posts` table, I'd love to be able to implement a `privacyLevel` column - 

```
enum PrivacyLevel {
    self
    friends
    public
}
```

**Comment by coco98** [comment]
Most of these have been handled. Closing this.
Enums at: https://docs.hasura.io/1.0/graphql/manual/schema/enums.html
