### ISSUE TITLE
Connection to postgres in docker with --net=host

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine-docs#32]
From https://github.com/hasura/graphql-engine/issues/140:

> @rikinsk Can you update the docs per: stackoverflow.com/questions/17770902/forward-host-port-to-docker-container/26090569#26090569
> Especially for this page I think: docs.hasura.io/1.0/graphql/manual/deployment/docker/index.html

**Comment by coco98** [comment]
I'm taking care of this.
