### ISSUE TITLE
Add direct links to binary downloads

### ISSUE THREAD

**Issue by mterron** [hasura/graphql-engine-docs#41]
hasura doesn't work at all on alpine linux. The installer fails because it can't find sudo even though it shouldn't need it. Manually installing the binary is ok, however it doesn't work, just returns with no output.

Also why do you need an install script with telemetry to download a single binary? That doesn't inspire confidence. Just add links to each arch you build and I'll put the binary somewhere it is convenient for my use case.

**Comment by shahidhk** [comment]
@mterron, you can find direct binary link on GitHub releases page.

**Comment by shahidhk** [comment]
We'll update docs to link to direct binary downloads also.
