### ISSUE TITLE
Integrating Hasura + Auth0

### ISSUE THREAD

**Issue by krishkumar** [hasura/graphql-engine-docs#44]
I am writing a how-to on creating a mobile backend with Hasura + Auth0. 

Following the instructions here to integrate Auth0 - https://github.com/hasura/sample-auth-webhook

In the final section "Usage with Hasura GraphQL engine", it is not clear what changes need to be made to the auth server. Specifically `https://github.com/hasura/sample-auth-webhook/blob/master/server.js#L46`

**Comment by coco98** [comment]
Hey there! You’re right. Its not clear that you need to configure a auth webhook for GraphQL engine too. If you’re using heroku, you need to set up the `HASURA_GRAPHQL_AUTH_HOOK` env var to be the URL of your auth webhook that you’ve setup.  Do let me know if you’re facing any issues here and well help you out. Docs should get updated very soon to fix this and make usage clear.

**Comment by krishkumar** [comment]
Thanks @coco98. 

I am going thru your examples. Here is what I have going already - 

1. Setup a Hasura GraphQL Engine instance `http://172.104.125.25:8080/` using https://docs.hasura.io/1.0/graphql/manual/deployment/docker/index.html

2. Setup auth0 webhook  `https://bpstudios-auth.herokuapp.com` by deploying https://github.com/hasura/sample-auth-webhook to Heroku.

What is not working is - 
`http://172.104.125.25:3000/home` setup via
https://github.com/wawhal/todo-app-graphql-engine-auth0

Specifically I am not able to make the todo react app talk to the graphql engine. Migrations on step 4 worked okay. I filled out the variables mentioned in step 5. The todo app was able to login to Auth0. 

But I don't see todos being created. I don't see any requests from the todo app in the dockers logs of the graphql engine.

**Comment by coco98** [comment]
I think the todo app might not be contacting the right endpoint. You'll have to configure the graphql endpoint in the todo app before you deploy it. Just to double check, what do you see happening on inspect element?

**Comment by krishkumar** [comment]
Inspect Element shows two errors - 

`[Error] Unhandled Promise Rejection: Error: Network error: JSON Parse error: Unexpected identifier "Not"
(anonymous function) (bundle.js:59794)	promiseReactionJob react-apollo.browser.umd.js:568`

`Failed to load resource: the server responded with a status of 404 (Not Found) http://172.104.125.25:8080`

**Comment by coco98** [comment]
Are you deploying the dame exact todo app that @wawhal had? I just tried it
ot for a demo and it works fine. :(

Can you also show the outgoing network request from inspect element?

**Comment by krishkumar** [comment]
Hmm I will try setting this up again and see if it works this time - 
https://github.com/hasura/sample-auth-webhook

[172.104.125.25-todocreation.txt](https://github.com/hasura/graphql-engine-docs/files/2216255/172.104.125.25-todocreation.txt)
[172.104.125.25-firstload.txt](https://github.com/hasura/graphql-engine-docs/files/2216256/172.104.125.25-firstload.txt)
