### ISSUE TITLE
Clarify the various configs/deployment methods

### ISSUE THREAD

**Issue by 2mol** [hasura/graphql-engine-docs#51]
I found it initially confusing to have settings I can change in `install-scripts/docker-compose.yaml`, `install-scripts/docker-run.sh` and also a bit in `config.yaml`. Clearly, _docker-run.sh_ won't read _config.yaml_, but I had to piece it together a bit.

I see this coming from the fact that I can have any combination of

- an existing postgres instance, or a new one, dockerized, composed with hasura.
- starting the console manually, or starting the console along with the `serve --enable-console`.

I also had to piece together a little bit that the latter gives me a console on 8080 instead of 9695. Maybe that's just my settings, since I run riwh `--net=host`?

Note that I don't have tons of experience with docker. The additional context of this is that I am replicating the instructions in the docs while being ssh'd into my remote server, not my local machine.

**Comment by shahidhk** [comment]
@2mol `config.yaml` and `migrations` are supposed to be used from a client, rather than on a server. `install_scripts` can be used to install graphql-engine on a server or on a client for quick testing. 

We'll update docs to make this clear.
