### ISSUE TITLE
Document support for different PostgreSQL flavours

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine-docs#72]
There are many flavors of postgresql which `graphql-engine` might support out of the box or with slight configuration/modifications. We need to document for each of them.

[TimescaleDB](https://github.com/timescale/timescaledb)
[CockroachDB](https://github.com/cockroachdb/cockroach)
[CitusDB](https://github.com/citusdata/citus)
[CrateDB](https://github.com/crate/crate)
[PostGIS](https://github.com/postgis/postgis)
[PipelineDB](https://github.com/pipelinedb/pipelinedb)

**Comment by ecthiender** [comment]
I have tested:

* Timescale: HGE works
* Citus: Our permission system doesn't work
* PostGIS: I think we have support for it already, if the extension is enabled on PG.

**Comment by shahidhk** [comment]
moved to https://github.com/hasura/graphql-engine/issues/411
