### ISSUE TITLE
[howto] integrate hasura with an existing nodejs backend

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine-docs#80]
(via matt donis through rajoshi)

> We currently make db calls directly from nodejs, can we replaces this with hasura?

**Comment by rikinsk** [comment]
@shahidhk @coco98 Doesn't this boil down to how to use graphql with nodejs? Or am I missing something

**Comment by shahidhk** [comment]
moved to https://github.com/hasura/graphql-engine/issues/316
